apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ggpgtk4ze-go 
  janus-idp.io/tekton: ggpgtk4ze-go
  backstage.io/kubernetes-id: ggpgtk4ze-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ggpgtk4ze-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml