apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ggpgtk4ze-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ggpgtk4ze-go 
  name: ggpgtk4ze-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ggpgtk4ze-go 
